language: node_js
node_js:
  - "4.3"
deploy:
  provider: s3
  access_key_id: AWS_ACCESS_KEY
  secret_access_key: AWS_SECRET_KEY
  bucket: blackmarkdown-web
  skip_cleanup: true
  acl: public_read
  upload-dir: dist
  region: ap-northeast-2
env:
  global:
  - secure: K8qNU95wcLpHqxZgU/QpSv619pJEMtXog8h7mwIuIz2xCqH4D+C6nSju0IAmJXmwYs/ab6Q+iEfVxrPDzo7tsNMshmRu0pZSsEw/PhJhvM2KH9mXIP4MhjDbT6TQGMwo7I16018pnmvErvsHqxWL46j9JRlg4wEVPT6UqxGGaQpsEpBXtBcxdq7TLV74ngRYWS5E7yUl3h2+pt2lE/HaUi0dMMuGeBVfCK4el76A+GudsK0gzwwGOkindcAE/zJjhnDk7NNIyIaSA/F8j28bcn7Q5xWUsD5IwqQZpU0PrUaWL7ZBIM87c1B4txaLOHmprzMWPUYt1WdnQMfM0TNxZEJ+b4MpPEIOTgU6WXomrEDmsXUvl3J/BeWZqFghG2UOMjVE4+TfLttQHySU0cQM1Rdg8kbhmTbvDFsXzHRa1RRitx9ApJasOEu2z5jMtaCZ2tzLuuwY34k5Nnp6TqC4LMB1mH8dUQYLMQIE007QqQLgUxyb948XyDqtlvy6YJNLaT8AeKwHm/MUY/UUAofn13i/2kGMHJDOZpgo5GPS8NnHuGF7/tDymxiJpJ6SJEi4b79yBuXeF5DFN/SQ8jxJoXC+5cYfWuic1L3DYw5muZkUtdmIIolF25jHL/+kVFJbVybBFDpj7WQKmDV0O4f+47w/W/5CQz5yneRmdJ6Dgqs=
  - secure: HaP9gQ6vUt1Rs7xGcb2CfCusYLz9Mt3wIUQ6bSxBbiVbmNAP6U6ffQ/4NC9LTtzbErzbAYTNaXD5GefYLsPoxPo+R83FycdTNaEBl8ECSJE8XbWzJ7xEtWoth4DypW759idaSzg5BvIRc5nfVPX+cbETR9/d8Qw/UFFACrLVeXpe+4PgKzY1MqtFeNjvosxB7UsNXxYN/z8HV+SJA/EMzrdZd0UDigw0zUuZaPQYiOJO11UKudPeFc54LURjZIbixqtW78WiWVTbUTsEX1xtTMi3piam0PW/uQxkr4omo0IbuhetNOOuYUMQyzz8ksvtPhhVpgv2jp6eBHHgtqWQWWpKs2u5my79WCPLt91ukWU4R6KHwsHEMe+GkS2IzFHsUsFReHEky1TiMS1jP1WJ0gXckjQauJBaO8h/GEKLCmgV1WWTIF6kX689QZMv1S69Z3hQKLtisCF5TA9eoP1iarUnlhvF06pGWh1GPYeNnDY0ajxJKO3Nu2JmYKjfxjZotpDmLSvvUhi+aTf2GpJrwNiUyXV7VKjMnnoMSoMOu0YOfpL44gVDTjFw+JBn81x4Ybn179F8q5dgINpwTut50MNzpTjxVpXGjszFlLp1L/pnKf5Hp8p7Re1U5zte4cOr3B6NTdx1c3x+18T98LeFmaCj3oHj2NizIJCJVdrq1Hs=
