language: node_js
node_js:
- '6.1'
install:
- npm i -g yarn && yarn
script: yarn build
deploy:
  provider: s3
  access_key_id: AKIAJ35YJLUUVSRIMUJA
  bucket: blackmarkdown-web
  skip_cleanup: true
  acl: public_read
  local_dir: dist
  region: ap-northeast-2
  secret_access_key:
    secure: gnC02Mi9fmM6492Ce1EtVcpSaQ7bE7pJsMsMdq9bw1Hqne0mPf/siNmbd0+gowERg6MdHMVFwKvTEQ3dqOjwQT/yYrTaH4wTGssVxoJquncjYUjr3SGlUDgkd2V0419Kqq7C5xIqOgRo//sMN0JYhYBTGrLcErc9ISQOVRi7qI9YDECCLQVZoaRWSfBb9I9/xlsUPPBgzaw6Gx0Zj94OiEOqZhOegJLAwVM3m6MlLZ6qAqJNacUvFIQS68TRxohWxbviZweIYkUWuWo2vVyiInF+Ai7mRJPHXVxCIRICA1ZrPxDi/005o94374OyLrq5dX14LojdbciHuJiZclTTGbRcM1iWGb4OYf7Z9ntMZq+zZTx2vLk4l5J4flRT8utmck3xRR9tgUbtx/sf6R9YJWBslotGwF0BJcCFrz2W9hvpMQVX4Pl5/GzC+fqKT9ct7GZPdVjPeJJRuDt06H6yJbr7ULUUytK8n4rclXC/lhAPGCoTBRw2fZNjCsYH25zcmqC0hdLr13NIYPCZoc30DDS8WMhA1/R3RdWbn+D0k03JdOlES06IUsHLelQcfKHhwQb5IQUBg8qRw5T8LJmxM5ZBIx0FxCLfUeTVim0aiSoM5KWgvdLHJENZuAB6eRxSGPd5MFUURLWIpYLblkCcKyr++1uxN3rcT3uqG0cjFhE=
