const ObjectType = {
  FOLDER: 'OBJECT_TYPE_FOLDER',
  PUBLIC_FILE: 'OBJECT_TYPE_PUBLIC_FILE',
  DRAFT_FILE: 'OBJECT_TYPE_DRAFT_FILE',
  IMAGE_FILE: 'OBJECT_TYPE_IMAGE_FILE',
};

export default ObjectType;
